services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: FrJroot
      POSTGRES_PASSWORD: FrJroot
      POSTGRES_DB: YouVento
    ports: 
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: FrJ@root.com
      PGADMIN_DEFAULT_PASSWORD: FrJroot
    ports:
      - "8081:80"

  php:
    build:
      context: ./PHP
      dockerfile: DockerFile
    container_name: php_container
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"